[tool.poetry]
name = "picasso test"
version = "1.0"
description = "Picasso Test"
authors = ["Александр Рассыхаев <farexzon@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
